In [1]:
import pandas as pd
import json
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import numpy as np

In [ ]:
'''Comport EDA and modellings '''

In [2]:
df=pd.read_json('files/data.json')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14337 entries, 0 to 14336
Data columns (total 44 columns):
acct_type             14337 non-null object
approx_payout_date    14337 non-null int64
body_length           14337 non-null int64
channels              14337 non-null int64
country               14256 non-null object
currency              14337 non-null object
delivery_method       14321 non-null float64
description           14337 non-null object
email_domain          14337 non-null object
event_created         14337 non-null int64
event_end             14337 non-null int64
event_published       14238 non-null float64
event_start           14337 non-null int64
fb_published          14337 non-null int64
gts                   14337 non-null float64
has_analytics         14337 non-null int64
has_header            8928 non-null float64
has_logo              14337 non-null int64
listed                14337 non-null object
name                  14337 non-null object
name_length           14337 non-null int64
num_order             14337 non-null int64
num_payouts           14337 non-null int64
object_id             14337 non-null int64
org_desc              14337 non-null object
org_facebook          14278 non-null float64
org_name              14337 non-null object
org_twitter           14278 non-null float64
payee_name            14337 non-null object
payout_type           14337 non-null object
previous_payouts      14337 non-null object
sale_duration         14182 non-null float64
sale_duration2        14337 non-null int64
show_map              14337 non-null int64
ticket_types          14337 non-null object
user_age              14337 non-null int64
user_created          14337 non-null int64
user_type             14337 non-null int64
venue_address         14337 non-null object
venue_country         13261 non-null object
venue_latitude        13261 non-null float64
venue_longitude       13261 non-null float64
venue_name            13261 non-null object
venue_state           13261 non-null object
dtypes: float64(9), int64(18), object(17)
memory usage: 4.9+ MB

In [4]:
smalldf=df[['acct_type','payout_type','delivery_method','has_header','previous_payouts','channels','email_domain','user_type']]
smalldf['event_length']=df['event_end']-df['event_start']
smalldf.loc[(smalldf["acct_type"]=='fraudster_event')]

/Users/jeremygozlan/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,acct_type,payout_type,delivery_method,has_header,previous_payouts,channels,email_domain,user_type,event_length
0,fraudster_event,,0.0,1.0,[],5,gmail.com,1,36000
51,fraudster_event,CHECK,0.0,NaN,"[{u'name': u'Royal Princesses and Knights', u'...",6,cox.net,1,18000
149,fraudster_event,ACH,0.0,NaN,"[{u'name': u'', u'created': u'2012-05-09 03:21...",5,zumba-perth.com,1,5400
187,fraudster_event,,1.0,0.0,[],8,diversity-church.com,1,10800
202,fraudster_event,ACH,0.0,0.0,[],5,gmail.com,1,255600
206,fraudster_event,ACH,0.0,0.0,[],13,yahoo.com,4,10800
212,fraudster_event,,0.0,NaN,[],5,comcast.net,1,10800
219,fraudster_event,,0.0,NaN,[],11,gmail.com,1,68400
248,fraudster_event,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2012-11-25 03:20...",8,yahoo.co.uk,1,10800
250,fraudster_event,ACH,0.0,0.0,[],5,yahoo.ca,3,25200
259,fraudster_event,CHECK,0.0,NaN,[],0,gmail.com,3,10800
262,fraudster_event,ACH,0.0,NaN,"[{u'name': u'', u'created': u'2012-11-04 03:17...",0,19sieunhan.com,1,94556400
263,fraudster_event,ACH,0.0,NaN,[],8,mail.com,1,14400
272,fraudster_event,ACH,0.0,NaN,"[{u'name': u'', u'created': u'2012-12-20 03:15...",0,4asdkids.com,1,10800
275,fraudster_event,ACH,0.0,0.0,[],0,emgay.com,3,31633200
289,fraudster_event,,0.0,NaN,[],0,aol.com,1,10800
296,fraudster_event,,0.0,0.0,[],5,mail.com,1,1819800
307,fraudster_event,,0.0,NaN,[],0,live.com,3,10800
318,fraudster_event,ACH,0.0,NaN,"[{u'name': u'', u'created': u'2013-02-19 03:13...",6,ymail.com,1,21600
323,fraudster_event,ACH,0.0,0.0,[],5,gmail.com,1,68400
330,fraudster_event,,0.0,NaN,[],0,gmail.com,1,10800
364,fraudster_event,ACH,0.0,0.0,[],11,outlook.com,1,5400
367,fraudster_event,ACH,0.0,0.0,[],0,gmail.com,1,97200
386,fraudster_event,ACH,0.0,NaN,[],5,yahoo.com,1,14400
440,fraudster_event,,0.0,NaN,[],5,live.com,4,10800
448,fraudster_event,ACH,0.0,NaN,[],0,maroclancers.com,1,1800
451,fraudster_event,,0.0,NaN,[],6,gmail.com,1,10800
457,fraudster_event,,0.0,NaN,[],0,hotmail.fr,3,10800
463,fraudster_event,ACH,0.0,NaN,[],6,gmail.com,1,18000
487,fraudster_event,,0.0,NaN,[],6,gmail.com,1,10800
...,...,...,...,...,...,...,...,...,...
13813,fraudster_event,,0.0,NaN,[],0,yahoo.com,1,16200
13864,fraudster_event,ACH,0.0,NaN,[],6,lushsaturdays.co.uk,1,93600
13871,fraudster_event,,0.0,NaN,[],8,fridayzonmarz.co.uk,1,21600
13909,fraudster_event,ACH,0.0,NaN,"[{u'name': u'', u'created': u'2013-05-18 03:21...",0,hotmail.com,1,10800
13944,fraudster_event,,0.0,NaN,[],0,live.fr,4,10800
13982,fraudster_event,,1.0,NaN,[],8,yahoo.com,3,7200
13992,fraudster_event,,1.0,0.0,[],8,yahoo.com,3,10800
13993,fraudster_event,ACH,0.0,NaN,[],0,yahoo.com,1,10800
13995,fraudster_event,ACH,0.0,NaN,[],0,gmx.com,1,10800
13998,fraudster_event,ACH,0.0,NaN,[],5,yahoo.com,1,10800
13999,fraudster_event,,0.0,NaN,[],0,live.com,1,25200
14000,fraudster_event,,0.0,0.0,[],6,yahoo.com,3,14400
14037,fraudster_event,ACH,0.0,0.0,[],0,hotmail.com,1,3600
14043,fraudster_event,ACH,1.0,0.0,[],5,cannapro.com,1,100800
14140,fraudster_event,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2012-04-17 00:00...",5,yahoo.ca,1,14400
14149,fraudster_event,,0.0,0.0,[],6,gmail.com,1,36000
14164,fraudster_event,ACH,0.0,NaN,[],10,yahoo.com,1,10800
14203,fraudster_event,,0.0,0.0,[],0,yahoo.com,3,10800
14229,fraudster_event,ACH,0.0,NaN,[],5,aol.com,3,18000
14235,fraudster_event,,0.0,NaN,[],0,yahoo.com,3,10800
14251,fraudster_event,ACH,0.0,NaN,[],5,yahoo.com,1,104400
14255,fraudster_event,ACH,0.0,NaN,[],0,yahoo.com,1,14400
14271,fraudster_event,ACH,0.0,NaN,"[{u'name': u'', u'created': u'2012-11-02 03:19...",0,gmail.com,1,18000
14297,fraudster_event,,0.0,0.0,[],5,thinktankconsultancy.com,1,7200
14304,fraudster_event,,0.0,0.0,[],0,usa.com,3,2696400
14316,fraudster_event,ACH,0.0,0.0,[],4,hotmail.co.uk,1,18000
14318,fraudster_event,,0.0,NaN,[],0,gmail.com,1,10800
14325,fraudster_event,,0.0,NaN,[],0,gmail.com,1,12600
14332,fraudster_event,,0.0,NaN,[],0,yahoo.com,1,25200
14336,fraudster_event,ACH,0.0,NaN,[],0,gmail.com,1,2147400

In [5]:
smalldf2=df[['acct_type','payout_type','delivery_method','has_header','previous_payouts','email_domain','channels','user_type']]
smalldf2['event_length']=df['event_end']-df['event_start']
smalldf2.loc[(smalldf2["acct_type"]=='premium')]

/Users/jeremygozlan/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,acct_type,payout_type,delivery_method,has_header,previous_payouts,email_domain,channels,user_type,event_length
1,premium,CHECK,1.0,0.0,"[{u'name': u'RUF', u'created': u'2010-10-01 01...",ruf.org,0,3,32400
2,premium,CHECK,1.0,NaN,"[{u'name': u'Danielle Severn', u'created': u'2...",pvsd.k12.ca.us,8,3,27000
3,premium,ACH,1.0,0.0,"[{u'name': u'', u'created': u'2010-11-09 01:10...",irishtabletennis.com,6,3,27831600
4,premium,CHECK,0.0,0.0,[{u'name': u'Arts and Business Council or Grea...,artsandbusinesscouncil.org,11,3,28800
5,premium,CHECK,0.0,0.0,"[{u'name': u'Bluegrass Stallions', u'created':...",bluegrassstallions.com,6,1,10800
6,premium,ACH,1.0,1.0,"[{u'name': u'', u'created': u'2011-01-12 01:12...",naboe.org,5,3,9000
7,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2011-01-25 01:12...",themagnetictheatre.org,12,3,5400
8,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2011-02-19 01:12...",credosf.com,4,3,16200
9,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2011-01-25 01:12...",themagnetictheatre.org,12,3,5400
10,premium,CHECK,1.0,0.0,[{u'name': u'San Francisco Family Support Netw...,sffsn.org,8,3,11700
11,premium,ACH,1.0,0.0,"[{u'name': u'', u'created': u'2010-09-22 01:10...",foragesf.com,10,3,7200
12,premium,CHECK,1.0,0.0,"[{u'name': u'DG Group, LLC', u'created': u'201...",dianagats.com,8,4,9000
14,premium,CHECK,0.0,0.0,"[{u'name': u'Simply Inc.', u'created': u'2010-...",simplystylist.com,11,3,10800
15,premium,CHECK,0.0,1.0,"[{u'name': u'Reel Link Films', u'created': u'2...",racetonowhere.com,6,3,7200
16,premium,CHECK,0.0,1.0,"[{u'name': u'Reel Link Films', u'created': u'2...",racetonowhere.com,6,3,7200
17,premium,CHECK,0.0,0.0,[{u'name': u'Friends of South Berwick Library'...,comcast.net,5,1,7200
18,premium,ACH,1.0,0.0,"[{u'name': u'IPCybercrime.com LLC', u'created'...",ipcybercrime.com,11,4,25200
19,premium,ACH,1.0,0.0,"[{u'name': u'', u'created': u'2011-03-06 01:13...",membersofmelange.com,6,3,18000
20,premium,ACH,1.0,1.0,"[{u'name': u'', u'created': u'2011-04-08 01:14...",ecufilmfestival.com,6,3,187200
21,premium,CHECK,0.0,0.0,"[{u'name': u'Percussion Center', u'created': u...",percussiononline.com,5,3,3600
22,premium,CHECK,0.0,NaN,[{u'name': u'Calvary Christian Reformed Church...,gmail.com,5,3,97200
23,premium,CHECK,1.0,0.0,"[{u'name': u'First American Title', u'created'...",firstam.com,8,3,10800
24,premium,CHECK,0.0,1.0,"[{u'name': u'Digital Eye Studios', u'created':...",digitaleyemedia.com,6,3,9000
25,premium,ACH,1.0,0.0,"[{u'name': u'Brian Reiners', u'created': u'201...",yahoo.com,8,3,10800
27,premium,CHECK,1.0,0.0,[{u'name': u'Chicago Tribune (Care of Jenna La...,tribune.com,5,3,9000
28,premium,ACH,1.0,1.0,"[{u'name': u'', u'created': u'2011-01-20 01:12...",facialesthetics.org,11,4,115200
29,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2010-06-04 01:10...",yahoo.com,5,4,21600
30,premium,CHECK,1.0,0.0,[{u'name': u'Duke University (Fund Code 813137...,gmail.com,0,4,12600
31,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2011-02-03 01:11...",weplayers.org,12,3,12600
33,premium,ACH,1.0,0.0,"[{u'name': u'', u'created': u'2011-06-30 01:10...",hotmail.com,5,4,72000
...,...,...,...,...,...,...,...,...,...
14299,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2012-09-23 03:16...",yahoo.com,4,3,10800
14300,premium,CHECK,1.0,0.0,"[{u'name': u'SAFE in Hunterdon, Inc.', u'creat...",safeinhunterdon.org,11,3,10800
14301,premium,ACH,1.0,0.0,"[{u'name': u'', u'created': u'2012-06-10 03:20...",broomheath.co.uk,10,3,10800
14302,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2012-12-04 03:14...",manchestercakeclub.co.uk,4,3,7200
14303,premium,ACH,1.0,0.0,"[{u'name': u'', u'created': u'2013-03-25 03:18...",newforestnpa.gov.uk,10,3,7200
14305,premium,ACH,1.0,0.0,"[{u'name': u'', u'created': u'2013-03-25 03:18...",newforestnpa.gov.uk,10,3,7200
14307,premium,ACH,3.0,1.0,"[{u'name': u'', u'created': u'2012-03-03 00:00...",improvboston.com,6,3,5400
14308,premium,ACH,1.0,NaN,"[{u'name': u'', u'created': u'2012-05-24 03:13...",ibethel.org,8,3,10800
14309,premium,ACH,1.0,1.0,"[{u'name': u'', u'created': u'2012-03-13 03:13...",cleantechinvestor.com,5,3,118800
14310,premium,ACH,0.0,NaN,"[{u'name': u'', u'created': u'2013-02-10 03:11...",JourneyingFree.com,8,4,3600
14311,premium,CHECK,1.0,NaN,"[{u'name': u'Trinity Church of the Nazarene', ...",trinitychurchmp.com,11,3,25200
14312,premium,CHECK,1.0,NaN,"[{u'name': u'ABD Cycle Club', u'created': u'20...",abdcycling.com,9,3,118800
14313,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2011-10-28 01:11...",hotmail.com,5,4,61200
14314,premium,ACH,1.0,0.0,"[{u'name': u'', u'created': u'2011-01-31 01:12...",execulink.com,0,3,1209600
14315,premium,ACH,1.0,0.0,"[{u'name': u'', u'created': u'2012-04-20 03:14...",swinginutrecht.nl,8,3,5400
14317,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2011-02-27 01:11...",gmail.com,5,3,10800
14319,premium,CHECK,1.0,0.0,"[{u'name': u'The Arbinger Institute', u'create...",arbinger.com,8,1,4230000
14320,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2013-02-17 03:12...",newcastle-cu.com,12,1,9000
14321,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2011-02-07 01:12...",thefetch.com,5,4,9000
14322,premium,ACH,1.0,NaN,"[{u'name': u'', u'created': u'2013-04-16 00:00...",yahoo.com,11,3,21600
14323,premium,ACH,1.0,1.0,"[{u'name': u'', u'created': u'2013-01-20 03:11...",hq.bcs.org.uk,0,1,5400
14324,premium,ACH,0.0,NaN,"[{u'name': u'', u'created': u'2013-03-01 03:13...",gmail.com,6,1,23400
14326,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2013-04-24 03:18...",sbm.ie,8,3,7200
14327,premium,CHECK,1.0,0.0,"[{u'name': u'St. Cloud State University ', u'c...",stcloudstate.edu,8,3,720000
14328,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2012-07-04 03:14...",chatterboxsocialmedia.co.uk,5,4,3600
14329,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2012-07-04 03:14...",chatterboxsocialmedia.co.uk,8,4,3600
14330,premium,CHECK,0.0,0.0,[{u'name': u'Center for Spiritual Living- C.O....,gmail.com,11,1,14400
14331,premium,CHECK,1.0,0.0,"[{u'name': u'Revolution Group', u'created': u'...",revolutiongroup.com,5,3,14400
14333,premium,CHECK,1.0,1.0,"[{u'name': u'ARCS Foundation Inc., San Diego C...",me.com,5,4,10800
14334,premium,ACH,0.0,0.0,"[{u'name': u'', u'created': u'2013-05-16 03:26...",yahoo.com,13,4,21600

In [6]:
df.acct_type.unique()

array([u'fraudster_event', u'premium', u'spammer_warn', u'fraudster',
       u'spammer_limited', u'spammer_noinvite', u'locked', u'tos_lock',
       u'tos_warn', u'fraudster_att', u'spammer_web', u'spammer'], dtype=object)

In [7]:
df= df[df['user_type'].isin([1,3,4,5])]

In [8]:
df['fraud'] = df['acct_type'].apply(lambda x: 1 if x in ['fraudster','fraudster_event','fraudster_att'] else 0)

In [9]:
df['fraud']=df['fraud'].apply(lambda x: 1 if x==True else 0)

In [10]:
df['previous_payouts']=df['previous_payouts'].apply(lambda x : 1 if len(x)>=1 else 0)
def quantitySold(x):
    lst = [i["quantity_sold"] for i in x]
    return sum(lst)
df["quantity_sold"] = df["ticket_types"].apply(quantitySold)

In [11]:
df['generic_email']=df['email_domain'].apply(lambda x : 0 if  all(s not in x for s in ['aol', 'gmail', 'live','hotmail','yahoo','outlook']) else 1)

In [12]:
df['delivery_method']=df['delivery_method'].apply(lambda x: 1 if x>=1.0 else 0)

In [13]:
df=pd.get_dummies(df,columns=['user_type'])

In [14]:
df=df[['generic_email','previous_payouts','delivery_method','sale_duration2','quantity_sold','user_type_1','user_type_3','user_type_3','user_type_5','fraud']]

In [15]:
NotFraudCount=len(df.loc[df['fraud']==0])
FraudCount=len(df.loc[df['fraud']==1])
ToGo=NotFraudCount-FraudCount

In [16]:
sampledDf=df[df['fraud']==1].sample(ToGo, replace=True)

finalDf = pd.concat([df,sampledDf],ignore_index=True)
NotFraudCount=len(finalDf.loc[finalDf['fraud']==0])
FraudCount=len(finalDf.loc[finalDf['fraud']==1])
print NotFraudCount,FraudCount

13042 13042

In [17]:
y=finalDf.pop('fraud')
X=finalDf

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.2, random_state=41)

In [19]:
model=LogisticRegression()

In [20]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [21]:
y_predicted=model.predict(X_test)
model.score(X_test,y_test)

0.89610887483227908

In [22]:
from sklearn.metrics import f1_score,precision_score,recall_score

f=f1_score(y_test, y_predicted, average='macro')
p=precision_score(y_test, y_predicted, average='macro')
r=recall_score(y_test, y_predicted, average='macro')
print f,p,r

0.89579790052 0.899625423742 0.895674791495

In [23]:
X_trainNeural=X_train.as_matrix()
y_trainNeural=y_train.values

In [24]:
from keras.models import Sequential
from keras.layers import Dense, Activation
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=9))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Generate dummy data
import numpy as np


# Train the model, iterating on the data in batches of 32 samples
model.fit(X_trainNeural, y_trainNeural, epochs=10, batch_size=32)

Using TensorFlow backend.

Epoch 1/10
20867/20867 [==============================] - 1s - loss: 0.3311 - acc: 0.8995
Epoch 2/10
20867/20867 [==============================] - 1s - loss: 0.2035 - acc: 0.9341
Epoch 3/10
20867/20867 [==============================] - 1s - loss: 0.1926 - acc: 0.9385
Epoch 4/10
20867/20867 [==============================] - 1s - loss: 0.1838 - acc: 0.9405
Epoch 5/10
20867/20867 [==============================] - 1s - loss: 0.1838 - acc: 0.9407
Epoch 6/10
20867/20867 [==============================] - 1s - loss: 0.1780 - acc: 0.9423
Epoch 7/10
20867/20867 [==============================] - 1s - loss: 0.1762 - acc: 0.9430
Epoch 8/10
20867/20867 [==============================] - 1s - loss: 0.1766 - acc: 0.9432
Epoch 9/10
20867/20867 [==============================] - 1s - loss: 0.1703 - acc: 0.9438     - ETA: 1s
Epoch 10/10
20867/20867 [==============================] - 1s - loss: 0.1688 - acc: 0.9443

In [25]:
y_predictionNeural=model.predict_classes(X_test.as_matrix())

3616/5217 [===================>..........] - ETA: 0s

In [26]:
y_predictionNeural

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [27]:
f=f1_score(y_test, y_predictionNeural, average='macro')
p=precision_score(y_test, y_predictionNeural, average='macro')
r=recall_score(y_test, y_predictionNeural, average='macro')
print f,p,r

0.941640601887 0.943484298795 0.941446545336

In [29]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier

In [32]:
rf=RandomForestClassifier()
gb=GradientBoostingClassifier()
rf.fit(X_train,y_train)
gb.fit(X_train,y_train)
predictrf=rf.predict(X_test)
predictgb=gb.predict(X_test)

In [33]:
f=f1_score(y_test, predictrf, average='macro')
p=precision_score(y_test, predictrf, average='macro')
r=recall_score(y_test, predictrf, average='macro')
print f,p,r

0.987348916845 0.987547169811 0.987466767945

In [34]:
f=f1_score(y_test, predictgb, average='macro')
p=precision_score(y_test,predictgb, average='macro')
r=recall_score(y_test, predictgb, average='macro')
print f,p,r

0.947044337512 0.948109973486 0.946886107972